version: "3"
services:
  db:
    image: mariadb
    volumes:
      - /db_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=simplepw
    ports:
      - "3306:3306"
  wp:
    depends_on:
      - db
    image: wordpress:5.1.1-php7.3-apache
    ports:
      - "8080:80"
    restart: always
    working_dir: /var/www/html
    volumes:
      - ./dist/wp-content:/var/www/html/wp-content
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_PASSWORD=simplepw