version: "3.3"
services:
  wordpress:
    build:
      context: ./config/docker/wordpress
    volumes:
      - ./dist/wp-content:/var/www/html/wp-content
    ports:
      - "8080:80"
    restart: always
    working_dir: /var/www/html
    depends_on:
      - database
  database:
    build:
      context: ./config/docker/database
    volumes:
      - datab:/var/lib/mysql
    restart: always
  # composer:
  #   build:
  #     #Run this docker file
  #     context: ./config/docker/composer
  #   # image: composer/composer:php7
  #   restart: always
  #   # command: install
  #   volumes:
  #     - ./dist/wp-content:/var/www/html/wp-content
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - database
    restart: always
    ports:
      - 8181:80
    environment:
      PMA_HOST: database
      MYSQL_USER: bilcker
      MYSQL_PASSWORD: 200169316*Db
volumes:
    datab: {}