version: "3.3"
services:
  composer:
    # Runs dockerfile for composer and wordpress
    container_name: wp-composer
    depends_on:
      - database
    build:
      context: ./
    volumes:
      - ./dist/wp-content/themes/custom-theme/:/var/www/html/dist/wp-content/themes/custom-theme/
    restart: 'no'
    ports:
      - "8080:80"
    logging:
      driver: none
  database:
    container_name: wp-database
    build:
      context: ./config/docker/database
    volumes:
      - datab:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
  phpmyadmin:
    build:
        context: ./config/docker/phpmyadmin
    ports:
      - 8282:80
    restart: always
    depends_on:
      - database
volumes:
    datab: {}