# start with the phpMyAdmin
FROM phpmyadmin/phpmyadmin

# Set our environment variables for logging into wordpress
ENV PMA_HOST database
ENV MYSQL_USER bilcker
ENV MYSQL_PASSWORD 200169316*Db

# Expose a port to run on
EXPOSE 80