# start with the latest wordpress and php image
FROM wordpress:5.1.1-php7.3-apache

# Set our environment variables for logging into wordpress
ENV WORDPRESS_DB_HOST database:3306
ENV WORDPRESS_DB_USER bilcker
ENV WORDPRESS_DB_PASSWORD 200169316*Db

# Expose a port to run on
EXPOSE 80